name: Build LiteXLoader

on:
  push:
    branches:
      - main

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build LiteXLoader.Js
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: MSBuild.exe ./LiteXLoader/LiteXLoader.sln -property:Configuration=Js
      shell: bash
      
    - name: Build LiteXLoader.Lua
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: MSBuild.exe ./LiteXLoader/LiteXLoader.sln -property:Configuration=Lua
      shell: bash
      
    - name: MkDirs
      run: |
        mkdir D:/build
      shell: bash
      
    - name: Copy Files
      run: |
        cp -rf ./RELEASE/. D:/build
        rm -f D:/build/.gitignore
        
        cp -a ./LiteXLoader/Release/*.dll D:/build
        cp -a ./LiteXLoader/Release/*.pdb D:/build/lib
        cp -a ./LiteXLoader/BaseLib/BaseLib.js D:/build/lib
        cp -a ./LiteXLoader/BaseLib/BaseLib.lua D:/build/lib
      shell: bash
    
    - name: Upload BuildFiles
      uses: actions/upload-artifact@v1.0.0
      with:
        name: LiteXLoader
        path: D:/build
